SELECT id_equipo AS 'CÓDIGO DE EQUIPO' ,SUM(goles) AS 'TOTAL GOLES POR EQUIPO' ,SUM(puntos) AS 'TOTAL PUNTOS POR EQUIPO' , AVG(goles) AS 'PROMEDIO GOLES' ,AVG(puntos) AS 'PROMEDIO PUNTOS'
FROM resultado
GROUP BY id_equipo
ORDER BY SUM(puntos) DESC;